version: '3.8'

services:

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_PASS=${DB_PASS}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: rbacdb
    ports:
      - "5433:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge